spring:
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: ----
            client-secret: ----
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/linkedin

            scope:
              - r_liteprofile
              - r_emailaddress
              - w_member_social
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken